[debian]
dependencies = ["curl"]
install_command = "curl -fsSL https://apt.fury.io/wez/gpg.key | sudo gpg --yes --dearmor -o /usr/share/keyrings/wezterm-fury.gpg\necho 'deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *' | sudo tee /etc/apt/sources.list.d/wezterm.list\nsudo chmod 644 /usr/share/keyrings/wezterm-fury.gpg\nsudo apt update -y"
skip_if_exists = "/usr/share/keyrings/wezterm-fury.gpg"

[ubuntu]
dependencies = ["curl"]
install_command = "curl -fsSL https://apt.fury.io/wez/gpg.key | sudo gpg --yes --dearmor -o /usr/share/keyrings/wezterm-fury.gpg\necho 'deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *' | sudo tee /etc/apt/sources.list.d/wezterm.list\nsudo chmod 644 /usr/share/keyrings/wezterm-fury.gpg\nsudo apt update -y"
skip_if_exists = "/usr/share/keyrings/wezterm-fury.gpg"

[fedora]
install_command = "exit 1"

[arch]
install_command = "exit 1"
