[arch]
install_command = "grep -q '^\\[multilib\\]' /etc/pacman.conf || (sudo sed -i '/^\\[multilib\\]/,/Include/s/^#//' /etc/pacman.conf && sudo pacman -Syu)"

[ubuntu]
install_command = "exit 1"

[debian]
install_command = "exit 1"
