[ubuntu]
install_system = "chezmoi"
snap = "classic"

[arch]
install_system = "chezmoi"

[debian]
dependencies = ["curl"]
install_command = "sudo sh -c \"$(curl -fsLS get.chezmoi.io)\" -- -b /usr/local/bin"
skip_if_exists = "/usr/local/bin/chezmoi"
