[debian]
install_command = "sudo sed -i '/^[^#].* main/ {\n  /non-free/! s/main/& non-free/\n}' /etc/apt/sources.list && sudo apt update -y"

[ubuntu]
install_command = "exit 1"

[arch]
install_command = "exit 1"
