[ubuntu]
install_command = "echo \"Notion is not available on Ubuntu.\""

[debian]
install_command = "echo \"Notion is not available on Debian.\""

[arch]
install_system = "notion-app-electron"

[fedora]
install_command = "echo \"Notion is not available on Fedora.\""
