[ubuntu]
install_system = "md.obsidian.Obsidian"
flatpak = true

[debian]
install_system = "md.obsidian.Obsidian"
flatpak = true

[arch]
install_system = "obsidian"

[fedora]
install_system = "md.obsidian.Obsidian"
flatpak = true
