[ubuntu]
install_system = "org.libretro.RetroArch"
flatpak = true

[debian]
install_system = "org.libretro.RetroArch"
flatpak = true

[arch]
install_system = "libretro"

[fedora]
install_system = "org.libretro.RetroArch"
flatpak = true
