[ubuntu]
dependencies = ["apt-spotify"]
install_system = "spotify-client"

[debian]
dependencies = ["apt-spotify"]
install_system = "spotify-client"

[arch]
install_system = "spotify"

[fedora]
install_system = "com.spotify.Client"
flatpak = true
