[ubuntu]
dependencies = ["apt-steam"]
install_system = "steam-launcher"

[debian]
dependencies = ["apt-steam"]
install_system = "steam-launcher"

[arch]
dependencies = ["arch-multilib"]
install_system = "steam"
