[ubuntu]
install_system = "com.stremio.Stremio"
flatpak = true

[debian]
install_system = "com.stremio.Stremio"
flatpak = true

[arch]
install_system = "stremio"

[fedora]
install_system = "com.stremio.Stremio"
flatpak = true
