[ubuntu]
install_system = "org.telegram.desktop"
flatpak = true

[debian]
install_system = "org.telegram.desktop"
flatpak = true

[arch]
install_system = "telegram-desktop"

[fedora]
dependencies = ["rpmfusion"]
install_system = "telegram-desktop"
