[ubuntu]
install_system = "torbrowser-launcher"

[debian]
dependencies = ["debian-contrib"]
install_system = "torbrowser-launcher"

[arch]
install_system = "torbrowser-launcher"

[fedora]
install_system = "torbrowser-launcher"
