[ubuntu]
dependencies = ["curl"]
install_command = "curl -f https://zed.dev/install.sh | sh"

[debian]
dependencies = ["curl"]
install_command = "curl -f https://zed.dev/install.sh | sh"

[arch]
install_system = "zed"

[fedora]
dependencies = ["curl"]
install_command = "curl -f https://zed.dev/install.sh | sh"
